In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('hotel_dataset.csv')
df

                   City  Latitude  Longitude
0     Aamby Valley City       NaN        NaN
1              Abhaneri       NaN        NaN
2            Achooranam       NaN        NaN
3          Acharapakkam       NaN        NaN
4                Achrol       NaN        NaN
...                 ...       ...        ...
1090        Neil Island       NaN        NaN
1091      Nelliyampathy       NaN        NaN
1092        Nelamangala       NaN        NaN
1093            Nellore       NaN        NaN
1094           Netarhat       NaN        NaN

[1095 rows x 3 columns]

In [3]:
df_kaggle = pd.read_csv('hotel_dataset_kaggle.csv')
df_kaggle

,Hotel Name,Landmark,city,highlight_value,Description,hotel_star_rating,Room facilities,latitude,longitude,review_score,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Hotel Sennite,"Near Bus Stand, Abohar",Abohar,NaN,|less,1 star,NaN,30.146782,74.202694,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aarti Guest House,Abohar,Abohar,24 hour business centre|ADSL Internet service|...,|Aarti Guest House is locate in Abohar. As one...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hotel Sethi Residency,NaN,Abohar,24 Hour Check in-Icon|24/7 Power|Banqueting|Do...,|Hotel Sethi Residency offers cozy accommodati...,2 star,Hot/cold Water | Attached Bathroom,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Manwar Garden Resort,NaN,AbuRoad,NaN,NaN,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hotel Bhumi,opposite sai baba temple aburoad,AbuRoad,NaN,|less,1 star,NaN,0,0.000000,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20042,Hotel Sri Silver Inn,Bedford Road,Yercaud,24/7 Power|Extra Bed (On Request)|Front desk|P...,|Hotel Sri Silver Inn is situated in the beaut...,1 star,Telephone | Bathroom Toiletries | Television |...,11.7813,78.217700,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20043,Ziro Valley Resort,NaN,Ziro,NaN,|Ziro Valley Resort is situated in the beautif...,1 star,NaN,27.523662,93.835467,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20044,Hotel Blue Pine,Ziro,Ziro,NaN,|Hotel Blue Pine is situated in the beautiful ...,1 star,NaN,27.543026,93.807663,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20045,MAMA HOME STAY,NaN,Zuluk,NaN,| Hotel Mama Homestay is a budget property loc...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20046,Hotel Palbheu,NaN,Zuluk,24 hour room service|Car rental|Laundry|Parkin...,| Hotel Palbheu is a budget property located i...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
unique_cities = df_kaggle['city'].unique()

# Print unique cities
print(unique_cities)

['Abohar' 'AbuRoad' 'Agartala' 'Agra' 'Ahmedabad' 'Ahmednagar' 'Aizawl'
 'Ajmer' 'Akola' 'Alibagh' 'Aligarh' 'Alipura' 'Allahabad' 'Allepey'
 'Almora' 'Alwar' 'Amba' 'Ambaji' 'Ambala' 'Ambikapur' 'Amboli' 'Amravati'
 'Amreli' 'Amritsar' 'Anand' 'Anandpur Sahib' 'AnandpurSahib' 'Anantapur'
 'Andaman' 'Angul' 'Ankleshwar' 'Araku Valley' 'ArakuValley' 'Aritar'
 'Asansol' 'Ashoknagar' 'Athirapally' 'Auli' 'Aurangabad' 'Ayodhya'
 'Azamgarh' 'Badami' 'Baddi' 'Badrinath' 'Bagalkot' 'Bagdogra' 'Bageshwar'
 'Bahadurgarh' 'Baharampur' 'Bahraich' 'Bakkhali' 'Balaghat' 'Balangir'
 'Balasore' 'Banda' 'Bandhavgarh' 'Bandikui' 'Bandipur' 'Bangalore'
 'Banswara' 'Baramati' 'Barbil' 'Bareilley' 'Bargarh' 'Barkot' 'Barmer'
 'Barnala' 'Barog' 'Barot' 'Beawar' 'Beed' 'Behror' 'Bekal' 'Belgaum'
 'Bellary' 'Belur' 'Berhampur' 'Berhampur-West Bengal'
 'BerhampurWestBengal' 'Bhadrachalam' 'Bhadrak' 'Bhagalpur' 'Bhalukpong'
 'Bhandardara' 'Bhangarh' 'Bharatpur' 'Bharmour' 'Bharuch' 'Bhatinda'
 'Bhavnagar' 'Bheemeshwari' 'Bhilai' 'Bhilwara' 'Bhimavaram' 'Bhimtal'
 'Bhiwadi' 'Bhiwani' 'Bhojpur' 'Bhopal' 'Bhubaneshwar' 'Bhuj' 'Bhusawal'
 'Biaora' 'Bidar' 'Bijapur' 'Bikaner' 'Bilaspur' 'Bina' 'Binsar' 'Bir'
 'Bishnupur' 'Bodhgaya' 'Bokaro' 'Bordi' 'BR Hills' 'Buduan' 'Bulandshahr'
 'Buldhana' 'Bundi' 'Burdwan' 'Calicut' 'Chail' 'Chakrata'
 'ChambaHimachal' 'Chambal' 'ChambaUttaranchal' 'Chamoli' 'Chamrajnagar'
 'Chandigarh' 'Chandrapur' 'Chaukori' 'Chenganoor' 'Chennai'
 'Cherrapunjee' 'Chettinad' 'Chhatarpur' 'Chhindwara' 'Chidambaram'
 'Chikhaldara' 'Chikmagalur' 'Chintpurni' 'Chiplun' 'Chitradurga'
 'Chitrakoot' 'Chittoor' 'Chittorgarh' 'Chopta' 'Churu' 'Cochin'
 'Coimbatore' 'Cooch Behar' 'CoochBehar' 'Coonoor' 'Coorg' 'Corbett'
 'Cuttack' 'Dabhosa' 'Dahanu' 'Dahej' 'Dakor' 'Daksum' 'Dalhousie'
 'Daltonganj' 'Daman' 'Damdama' 'Dandeli' 'Dapoli' 'Darbhanga'
 'Darjeeling' 'Datia' 'Dausa' 'Davangere' 'Deesa' 'Dehradun' 'Deogarh'
 'DEOGHAR' 'Devprayag' 'Dewas' 'Dhampur' 'Dhamtari' 'Dhanaulti' 'Dhanbad'
 'Dhar' 'Dharamshala' 'Dharmavaram' 'Dharwad' 'Dholpur' 'Dhule'
 'Dibrugarh' 'Digha' 'Dimapur' 'Dindi' 'Dindigul' 'Dirang' 'Diu'
 'Diveagar' 'Dongargarh' 'Dooars' 'Dungarpur' 'Durg' 'Durgapur' 'Durshet'
 'Dwarika' 'East Sikkim' 'EastSikkim' 'Eluru' 'Ernakulum' 'Erode' 'Etawah'
 'Faizabad' 'Faridkot' 'Fatehabad' 'Fatehpur' 'Fatehpur Sikri'
 'FatehpurSikri' 'Fazilka' 'Ferozepur' 'Firozabad' 'Forbesganj' 'Gajraula'
 'Gandhidham' 'Gandhinagar' 'Gangavathi' 'Gangotri' 'Gangtok'
 'Ganpatipule' 'Gaya' 'Ghangaria' 'Giridih' 'Goa' 'Godda' 'Godhra'
 'Gokarna' 'Golaghat' 'Gondia' 'Gopalpur on sea' 'Gopalpuronsea'
 'Gorakhpur' 'Gudalur' 'Guhagar' 'Gulbarga' 'Gulmarg' 'Guna' 'Gundlupet'
 'Guntur' 'Guptkashi' 'Gurdaspur' 'Guruvayoor' 'Guwahati' 'Gwalior'
 'Haldia' 'Haldwani' 'Hampi' 'Hansi' 'Hanumangarh' 'Hardoi' 'Haridwar'
 'HarkiDun' 'Harnai' 'Hassan' 'Havelock' 'Haveri' 'Hazaribagh'
 'Himmatnagar' 'Hingoli' 'Hissar' 'Hodal' 'Hoshangabad' 'Hoshiarpur'
 'Hospet' 'Hosur' 'Howrah' 'Hubli' 'Hyderabad' 'Idduki' 'Igatpuri'
 'Imphal' 'Indore' 'Itanagar' 'Itarsi' 'Jabalpur' 'Jagdalpur' 'Jaipur'
 'Jaisalmer' 'Jajpur' 'Jalandhar' 'Jaldapara' 'Jalgaon' 'Jalna' 'Jalore'
 'Jalpaiguri' 'Jambughoda' 'Jammu' 'Jamnagar' 'Jamshedpur' 'JASIDIH'
 'Jaunpur' 'Jawalamukhi' 'Jawhar' 'Jhabua' 'Jhajjar' 'Jhalawar' 'Jhansi'
 'Jharsuguda' 'Jhumri Telaiya' 'JhumriTelaiya' 'Jhunjhunu' 'Jind'
 'Jodhpur' 'Jorhat' 'Joshimath' 'Junagarh' 'Jwalamukhi' 'Kabini' 'Kadapa'
 'Kaithal' 'Kakinada' 'Kalimpong' 'Kalka' 'Kalpa' 'Kanatal' 'Kanchipuram'
 'Kangra' 'Kanha' 'Kankavli' 'Kannur' 'Kanpur' 'Kanyakumari' 'Kapurthala'
 'Karad' 'Karaikal' 'Karaikudi' 'Karanprayag' 'Karauli' 'Kargil'
 'Karimnagar' 'Karjat' 'Karnal' 'Karsog' 'Karur' 'Karwar' 'Kasargod'
 'Kasauli' 'Kashid' 'Kashipur' 'Kasol' 'Katihar' 'Katni' 'Katra' 'Kausani'
 'Kavali' 'Kaza' 'Kaziranga' 'Kedarnath' 'Keonjhar' 'Keylong' 'Khajjiar'
 'Khajuraho' 'Khammam' 'Khandwa' 'Khanna' 'Kharagpur' 'Khatu' 'Khimsar'
 'Khopoli' 'Kinnaur' 'Kishangarh' 'Kodaikanal' 'Kohima' 'Kolhapur'
 'Kolkata' 'Kollam' 'Konark' 'Korba' 'Kosi' 'Kota' 'Kotagiri' 'Kotdwar'
 'Kotputli' 'Kottayam' 'Kovalam and Poovar' 'KovalamandPoovar'
 'Krishnagiri' 'Krishnanagar' 'Kudal' 'Kullu' 'Kumarakom' 'Kumbakonam'
 'Kumbalgarh' 'Kundapur' 'Kurnool' 'Kurseong' 'Kurukshetra' 'Kushinagar'
 'Kutch' 'Kuttikkanam' 'Lachen' 'Lachung' 'Ladakh' 'Lahaul' 'Lakhimpur'
 'Lakshadweep' 'Lalitpur' 'Lansdowne' 'Lataguri' 'Latur' 'Lava' 'Lavasa'
 'Leh' 'Loleygaon' 'Lonavala And Khandala' 'LonavalaAndKhandala' 'Lucknow'
 'Ludhiana' 'Madhopur' 'Madhubani' 'Madhupur' 'Madikeri' 'Madumalai'
 'Madurai' 'Mahabaleshwar' 'Mahabalipuram' 'Mahbubnagar' 'Maheshwar'
 'Maihar' 'Malappuram' 'Malda' 'Malegaon' 'Malerkotla' 'Malshej' 'Malvan'
 'Manali' 'Manas' 'Mandarmoni' 'Mandawa' 'Mandi' 'Mandi Gobindgarh'
 'Mandsaur' 'Mandu' 'Mangalore' 'Manipal' 'Mansa' 'ManzDoNotBook'
 'Masinagudi' 'Matheran' 'Mathura' 'Mayiladuthurai' 'Mayurbhanj'
 'Medinipur' 'Meerut' 'Mehsana' 'METTUPALAYAM' 'Mirik' 'Mirzapur' 'Modasa'
 'Moga' 'Mohali' 'Moradabad' 'Morbi' 'Mount Abu' 'MountAbu' 'Muktasar'
 'Mukteshwar' 'Mukutmanipur' 'Mumbai' 'Mundra' 'Munnar' 'Munsiyari'
 'Murshidabad' 'Murud Janjira' 'Murudeshwar' 'MurudJanjira' 'Mussoorie'
 'Muvattupuzha' 'Muzaffarnagar' 'Muzaffarpur' 'Mysore' 'Nadiad' 'Nagaon'
 'NAGAPATTINAM' 'NAGARCOIL' 'Nagarholae' 'Nagaur' 'Nagpur' 'Nahan'
 'Nainital' 'Najibabad' 'Nalagarh' 'Naldehra' 'Namakkal' 'Namchi' 'Nanded'
 'Nandurbar' 'Narkanda' 'Narnaul' 'Narsinghpur' 'Nasik' 'Nathdwara'
 'Naukuchiatal' 'Nawalgarh' 'Neemrana' 'Neemuch' 'Neil Island'
 'NeilIsland' 'Nellore' 'Neral' 'New Delhi And NCR' 'New Tehri'
 'NewDelhiAndNCR' 'NewTehri' 'Nilgiri' 'Nimaj' 'Nizamabad'
 'North Lakhimpur' 'NorthLakhimpur' 'Nubra Valley' 'NubraValley'
 'Omkareshwar' 'Ongole' 'Ooty' 'Orai' 'Orchha' 'Osian' 'Osmanabad'
 'Pachmarhi' 'Pahalgam' 'Palakkad' 'Palampur' 'Palani' 'Pali' 'Palwal'
 'Panchgani' 'Panchkula' 'Panchmarhi' 'Pandharpur' 'Pangong' 'Pangot'
 'Panhala' 'Panipat' 'Panna' 'Pantnagar' 'Panvel' 'Paonta Sahib'
 'Paradeep' 'Parbhani' 'Parwanoo' 'Pathanamthitta' 'Pathankot' 'Patiala'
 'Patna' 'Patnitop' 'Pauri' 'Pelling' 'Pench' 'Phagwara' 'Phalodi'
 'Phaltan' 'Phulbani' 'Pilibhit' 'Pinjore' 'Pipariya' 'Pithampur'
 'Pithoragarh' 'Pokhran' 'Pollachi' 'Pondicherry' 'Porbandar' 'Port Blair'
 'PortBlair' 'Pragpur' 'Proddatur' 'Pune' 'Puri' 'Pushkar' 'Puttaparthi'
 'Raibareilly' 'Raigad' 'Raigarh' 'Raipur' 'Rajahmundry' 'Rajgarh'
 'Rajgir' 'Rajkot' 'Rajnandgaon' 'Rajpura' 'Rajsamand' 'Rajula'
 'Rameshwaram' 'Ramgarh' 'Rampur' 'Ramtek' 'Ranakpur' 'Ranchi' 'Ranikhet'
 'Ranipet' 'Ranthambhore' 'Ratlam' 'Ratnagiri' 'Ravangla' 'Rewa' 'Rewari'
 'Rinchenpong' 'Rishikesh' 'Rishyap' 'Rohtak' 'Roorkee' 'Rourkela'
 'Rudraprayag' 'Rudrapur' 'Sagar' 'Sagara' 'Saharanpur' 'Sakleshpur'
 'Salasar' 'Salem' 'Samastipur' 'Sambalpur' 'Samode' 'Sanchore' 'Sangla'
 'Sangli' 'Sangrur' 'Sankri' 'Saputara' 'Sariska' 'Sasan Gir' 'SasanGir'
 'Satara' 'Satna' 'SawaiMadhopur' 'Sawaimadhopur' 'Sawantwadi'
 'Secunderabad' 'Seema' 'Sendhwa' 'Shahdol' 'Shahjahanpur' 'Shankarpur'
 'Shantiniketan' 'Sheopur' 'Shillong' 'Shimla' 'Shimoga' 'Shirdi'
 'Shivpuri' 'Shrivardhan' 'Sidhpur' 'Sikar' 'Silchar' 'SilentValley'
 'Siliguri' 'Silvassa' 'Sindhudurg' 'Singrauli' 'Sirmour' 'Sirohi' 'Sirsa'
 'Sirsi' 'SIVAKASI' 'Solan' 'Solapur' 'Sombariea' 'Somnath' 'Sonamarg'
 'Sonepat' 'Sonipat' 'Sri Ganganagar' 'SriGanganagar' 'Srikakulam'
 'Srikalahasti' 'Srinagar' 'SrinagarGarhwal' 'Sriperumbudur' 'Srisailam'
 'Subramanya' 'Sultanpur' 'Sumerpur' 'Sunderban' 'Surajgarh' 'Surat'
 'Suratgarh' 'Tadepalligudem' 'Tadoba' 'Takdah' 'Tamia' 'Tanakpur'
 'Tanjore' 'Tarapith' 'Tarkali' 'Tezpur' 'Thalasserry' 'Thane' 'Thanjavur'
 'Thattekkad' 'Thekkady' 'Theni' 'Thiruvananthapuram' 'Thiruvannamalai'
 'Thodupuzha' 'Thrissur' 'Tinsukia' 'TIRUCHENDUR' 'Tiruchirapally'
 'Tirunelveli' 'Tirupati' 'Tirupur' 'Tiruttani' 'Tiruvannamalai' 'Tumkur'
 'Tuticorin' 'Udaigiri' 'Udaipur' 'Udhampur' 'Udupi' 'Ujjain' 'Umargam'
 'Una' 'Uttarkashi' 'Vadodara' 'Vagamon' 'Vailankanni' 'Valparai' 'Valsad'
 'Vapi' 'Varanasi' 'Varkala' 'Vellore' 'Vengurla' 'Veraval' 'Vidisha'
 'Vijaywada' 'Vinukonda' 'Vishakhapatnam' 'Vizianagram' 'Wada' 'Warangal'
 'Wardha' 'Washim' 'Wayanad' 'WeekendGetawaysAroundBangalore'
 'WeekendGetawaysAroundChandigarh' 'WeekendGetawaysAroundChennai'
 'WeekendGetawaysAroundDelhi' 'WeekendGetawaysAroundHyderabad'
 'WeekendGetawaysAroundMumbai' 'WeekendGetawaysAroundPune' 'West Sikkim'
 'WestSikkim' 'Yamnotri' 'Yamunanagar' 'Yanam' 'Yavatmal' 'Yelagiri'
 'Yercaud' 'Ziro' 'Zuluk']

In [8]:
cities = list(df['City'])
print(cities)

['Aamby Valley City', 'Abhaneri', 'Achooranam', 'Acharapakkam', 'Achrol', 'Adilabad', 'Adimaly', 'Adipur', 'Adoni', 'Adoor', 'Agartala', 'Agatti', 'Goa', 'Agra', 'Agumbe', 'Etmadpur', 'Ahmedabad', 'Kalol', 'Ahmednagar', 'Aizawl', 'Ahwa', 'Ajanta', 'Ajmer', 'Pushkar', 'Nimbahera', 'Kolkata', 'Akluj', 'Alampur', 'Akola', 'Alandi', 'Alappuzha', 'Kainakary', 'Pulinkunnu', 'Alchi', 'Alibaug', 'Aligarh', 'Alipurduar', 'Allahabad', 'Alirajpur', 'Almora', 'Alwar', 'Along', 'Amalapuram', 'Amaravathi', 'Amarkantak', 'Ambaji', 'Ambajogai', 'Ambala', 'Ambalappuzha', 'Ambarnath', 'Ambikapur', 'Amravati', 'Ambur', 'Amboli', 'Amritsar', 'Amreli', 'Anandpur Sahib', 'Anakulam', 'Anand', 'Vallabh Vidyanagar', 'Anantapur', 'Anantnag', 'Anaviratty', 'Andhakaranazhy', 'Andanallur', 'Angul', 'Anchal', 'Andretta', 'Anjarle', 'Anjanvel', 'Anjar', 'Annavaram', 'Ankleshwar', 'Ankola', 'Antarvedi', 'Araku Valley', 'Aragonda', 'Arakkonam', 'Aritar', 'Arayankavu', 'Ariyurnadu', 'Ariyankuppam', 'Aronda', 'Arki', 'Asansol', 'Athirappilly', 'Astakatti', 'Athipotta', 'Auli', 'Attingal', 'Joshimath', 'Aurangabad', 'Auroville', 'Ausa', 'Awantipora', 'Avakali', 'Ayodhya', 'Aversa', 'Ayyampuzha', 'Azheekal', 'Baba Bakala', 'Azhikode', 'Azamgarh', 'Badami', 'Badgam', 'Badlapur', 'Badrinath', 'Bagalkot', 'Bagdogra', 'Bageshwar', 'Baghpat', 'Bagru', 'Bahraich', 'Bahadurgarh', 'Baijnath', 'Bajarwadi', 'Keori', 'Bakkhali', 'Bajaura', 'Balasinor', 'Balangir', 'Balasore', 'Balgudar', 'Balicha', 'Balurghat', 'Balotra', 'Banavasi', 'Bandhavgarh National Park', 'North', 'Tala', 'Bandipur National Park', 'Bandipur', 'Bangaram', 'Baneshwar', 'Banjar', 'Bankura', 'Bannari', 'Banswara', 'Banni', 'Bantwal', 'Bapatla', 'Baramati', 'Barabanki', 'Baramulla', 'Baran', 'Barasat', 'Baratang Island', 'Barddhaman', 'Bareilly', 'Bardoli', 'Bargarh', 'Baripada', 'Barmer', 'Barog', 'Barpeta', 'Barrackpur', 'Barua Sagar', 'Bastar', 'Barwani', 'Barshi', 'Bassi', 'Basti', 'Bathinda', 'Batala', 'Bataw', 'Beed', 'Bekal', 'Begusarai', 'Belakavadi', 'Belgaum', 'Bellary', 'Belluru', 'Belthangady', 'Belur', 'Bengaluru', 'Bera', 'Bhadrachalam', 'Betul', 'Beypore', 'Bhabhua', 'Bhadrak', 'Bhagalpur', 'Bhadravati', 'Bhagsu Nag', 'Bhagani', 'Bhagdara', 'Bhandara', 'Bhalukpong', 'Bhairapur', 'Bhalki', 'Bhandardara', 'Bharatpur', 'Bharmour', 'Bharuch', 'Bhatkal', 'Bhavani', 'Bhavnagar', 'Bhawanipatna', 'Bhilai', 'Bhilwara', 'Bhildi', 'Bhimashankar', 'Bhimavaram', 'Bhimtal', 'Bhinar', 'Bhind', 'Bhitarkanika National Park', 'Bhiwadi', 'Bhiwandi', 'Bhiwani', 'Bhojpur', 'Bhopal', 'Bhowali', 'Bhubaneswar', 'Bhuj', 'Bhuvanagiri', 'Bhuntar', 'Bhusawal', 'Bidar', 'Bidadi', 'Bidarakatte', 'Bijapur', 'Bijolia', 'Bikaner', 'Bilaspur', 'Bikkavolu', 'Bilimora', 'Binsar', 'Birpara', 'Bir', 'Bishnupur', 'Bodh Gaya', 'Blathykavala', 'Bokakhat', 'Boisar', 'Bokaro Steel City', 'Bolpur', 'Bomdila', 'Bongaigaon', 'Bordi', 'Borsad', 'Brahmadesam', 'Borid', 'Brahmapur', 'Budhauli', 'Budaun', 'Buldana', 'Bulandshahr', 'Bundi', 'Burhanpur', 'Burdwan', 'Burwa', 'Buxar', 'Byndoor', 'Canning', 'Chaibasa', 'Chakrata', 'Chalakudy', 'Chamarajanagar', 'Chamba', 'Chamoli', 'Champaner', 'Champawat', 'Champhai', 'Chandannagar', 'Chamrajnagar', 'Chandauli', 'Chanderi', 'Chandigarh', 'Panchkula', 'Zirakpur', 'Ramgarh', 'Chandipur', 'Chandrapur', 'Chandragutti', 'Changanacherry', 'Changlang', 'Channapatna', 'Channarayapatna', 'Chapagaon', 'Chatra', 'Chaukori', 'Chelamattom part', 'Chendamangalam', 'Chengalpattu', 'Chengannur', 'Chennai', 'Vypin Island', 'Sohra', 'Cherthala', 'Cheyyar', 'Cheruthuruthi', 'Chettikulam', 'Chhatarpur', 'Chhachhrauli', 'Chhindwara', 'Chhatikara', 'Chidambaram', 'Chikhaldara', 'Chikkaballapur', 'Chikka Madhure', 'Chikmagalur', 'Halebid', 'Chinchoti', 'Chinnamanur', 'Chiplun', 'Chindi', 'Chinsurah', 'Chintamani', 'Chintpurni', 'Chirala', 'Chitkul', 'Chitradurga', 'Chitrakoot', 'Chittaurgarh', 'Chittoor', 'Chittorgarh', 'Chowara', 'Chopta', 'Chorla', 'Chorwad', 'Chundale', 'Chumathang', 'Churu', 'Chuntang', 'Churachandpur', 'Coimbatore', 'Cola', 'Cooch Behar', 'Contai', 'Coonoor', 'Courtallam', 'Covelong', 'Cuddalore', 'Cumbum', 'Cuttack', 'Maina', 'Dabaspete', 'Dabguli', 'Dabhoi', 'Dahanu', 'Dahod', 'Dakor', 'Dahej', 'Dalhousie', 'Daman', 'Daltonganj', 'Dandeli', 'Damoy', 'Danapur', 'Dapoli', 'Dandi', 'Dantewada', 'Darbhanga', 'Upper Subansiri District', 'Darjeeling', 'Darima', 'Datia', 'Dasanapura', 'Daulatabad', 'Dausa', 'Davanagere', 'Davangere', 'Dawki', 'Deeg', 'Dehgam', 'Deesa', 'Dehradun', 'Denkanikottai', 'Delwara', 'Deoghar', 'Deogarh', 'Deshnoke', 'Deoria', 'Deo', 'Devanhalli', 'Devadhanapatti', 'Devarayanadurga', 'Devikulam', 'Devipattinam', 'Devprayag', 'Dewas', 'Dhamtari', 'Dhali', 'Dhanaulti', 'Dhanbad', 'Dhankhar', 'Dharamkot', ' Dharamshala ', 'McLeod Ganj', 'Tapovan', 'Jwalamukhi', 'Kangra', 'Khaniyara', 'Dharapuram', 'Dharchula', 'Dharmapuri', 'Dhari', 'Dharmasthala', 'Dhar', 'Dharuhera', 'Dhaulas', 'Dhaula Kuan', 'Dhenkanal', 'Dhemaji', 'Dholpur', 'Dhikuli', 'Dhubri', 'Dhule', 'Dibrugarh', 'Digboi', 'Digha', 'North Andaman Island', 'Dimapur', 'Dindigul', 'Dirang', 'Dindori', 'Diphu', 'Diskit', 'Dispur', 'Diu', 'Diveagar', 'Doddaballapur', 'Doda', 'Dombivli', 'Draksharama', 'Dongargarh', 'Dudhwa National Park', 'Dubrajpur', 'Duhka', 'Dumka', 'Dungarpur', 'Durgapur', 'Durg', 'Dwaraka Tirumala', 'Dwarka', 'Ellora', 'Dyathapura', 'Egatoor', 'Eluru', 'Erimayur-II', 'Erode', 'Eppodumvenran', 'Fagu', 'Ezhome', 'Faizabad', 'Etawah', 'Faridabad', 'Falna', 'Farakka', 'Faridkot', 'Fatehpur Sikri', 'Farsaheya', 'Fatehgarh', 'Fatehpur', 'Fazilka', 'Ferozpur Jhirka', 'Firozabad', 'Firozpur', 'Gadag', 'Gadwal', 'Gajner', 'Gandhidham', 'Ganagapur', 'Gandhinagar', 'Galajwari', 'Gandikota', 'Ganeshgudi', 'Gangolihat', 'Gangotri', 'Sagar Island', 'Gangtok', 'Tadong', 'Ganjam', 'Ganpatipule', 'Malgund', 'Garbeta', 'Garhwal', 'Garh Siliyara', 'Garjiya', 'Gaya', 'Garoi', 'Garhwa', 'Geyzing', 'Ghatgan', 'Ghatshila', 'Ghanerao', 'Ghagra', 'Ghaziabad', 'Gingee', 'Ghazipur', 'Gholu Majra', 'Sasan Gir', 'Gir National Park', 'Giridih', 'Gobichettipalayam', 'Gokak', 'Godda', 'Gokarna', 'Golaghat', 'Gondal', 'Gondia', 'Gopalpur On Sea', 'Gopalpur', 'Gopeshwar', 'Gorakhpur', 'Gorumara National Park', 'Gorubathan', 'Gosaba', 'Gotagodi', 'Govardhan', 'Greater Noida', 'Great Nicobar Island', 'Gudalur', 'Gubbi', 'Guhagar', 'Gudur', 'Gulbarga', 'Gulmarg', 'Guna', 'Guntur', 'Gumla', 'Guptkashi', 'Gurdaspur', 'Gurugram (Gurgaon)', 'New Delhi', 'Guruvayur', 'Guwahati', 'Gwalior', 'Gwaldam', 'Gyaraspur', 'Haddo', 'Haflong', 'Haldia', 'Habra', 'Hajipur', 'Hajo', 'Haldwani', 'Hamirpur', 'Hampi', 'Halol', 'Hanle', 'Hansi', 'Hanumangarh', 'Haorang Sabal', 'Hanumanthapuram', 'Haridwar', 'Hardoi', 'Shivpuri', 'Harihar', 'Harigar', 'Harnai', 'Haroa', 'Haripurdhar', 'Hassan', 'Hastinapur', 'Hatgad', 'Havelock Island', 'Hatkoti', 'Haveri', 'Hazaribagh', 'Hazira', 'Hemis', 'Himmatnagar', 'Hiala', 'Hingoli', 'Hingolgadh Village', 'Hinjewadi', 'Hisar', 'Hogenakkal', 'Honnavar', 'Hooghly', 'Horanadu', 'Hoovina Hadagalli Taluk', 'Hosadurga', 'Hoshangabad', 'Hoshiarpur', 'Hospet', 'Hosur', 'Howrah', 'Hubli-Dharwad', 'Hunder', 'Hundur', 'Hunsur', 'Huzurnagar', 'Hyderabad', 'Idagunji', 'Kumily', 'Idar', 'Anachal', 'Idukki', 'Munnar', 'Nedumkandam', 'Igatpuri', 'Imphal', 'Indore', 'Indapur', 'Itanagar', 'Injole', 'Irikkur', 'Jabalpur', 'Itarsi', 'Jadupur', 'Jagdalpur', 'Jagadhri', 'Jageshwar', 'Jaggaiahpet', 'Jaipur', 'Jaigaon', 'Jagraon', 'Amer', 'Jaisalmer', 'Jajpur', 'Jalandhar', 'Jakrem', 'Jalgaon', 'Jalasangvi', 'Jalna', 'Jalore', 'Jalpaiguri', 'Jambughoda', 'Jambusar', 'Jammu City', 'Jamnagar', 'Jamshedpur', 'Janakpuri', 'Jamui', 'Janjgir', 'Jamtara', 'Jashpur', 'Jariput', 'Jaunpur', 'Jawhar', 'Jawahar', 'Jejuri', 'Jetpur', 'Jeypore', 'Jhajjar', 'Jhalawar', 'Jhansi', 'Jhalrapatan', 'Jharsuguda', 'Jhargram', 'Jhunjhunu', 'Jim Corbett National Park', 'Jibhi', 'Ramnagar', 'Jodhpur', 'Joginder Nagar', 'Jolaibari', 'Jorhat', 'Jowai', 'Junagadh', 'Jubbal', 'Junnar', 'Kadapa', 'Kadi', 'Kadayam', 'Kadiri', 'Kakinada', 'Kailashahar', 'Kaikaluru', 'Kaipadar', 'Kakkabe', 'Kaladhungi', 'Kalady', 'Kalasa', 'Kaleshwaram', 'Kalimpong', 'Kallar', 'Kalka', 'Kalna', 'Kalpa', 'Kalpetta', 'Kalsi', 'Kalyan', 'Kalyani', 'Kamargaon', 'Kamarpukur', 'Kammasandra', 'Kamavarapukota', 'Kamshet', 'Kamod', 'Kanakapura', 'Kanadukathan', 'Kanchipuram', 'Chail', 'Kanger Valley National Park', 'Kangar Dharyar', 'Kandla', 'Kanha National Park', 'Kanhangad', 'Kanipakam', 'Kanjirappally', 'Kannan Devan Hills', 'Kanker', 'Kannad', 'Kannauj', 'Kannur', 'Thottada', 'Kanoi', 'Kanpur', 'Kanyakumari', 'Kanthalloor', 'Kantilo', 'Kapurthala', 'Karad', 'Karaikal', 'Karaikudi', 'Karauli', 'Kargil', 'Lamayuru', 'Karimnagar', 'Karjat Town', 'Neral', 'Karkala', 'Karnala', 'Karnal', 'Karsha', 'Karsog', 'Karur', 'Karuvarakundu', 'Karwar', 'Kasaragod', 'Dharampur', 'Kasarkod', 'Kasauli', 'Kashid', 'Kashipur', 'Kasol', 'Kas', 'Kathua', 'Katni', 'Katra', 'Katoya', 'Kausani', 'Kattoor', 'Kaushambi', 'Kavaratti Island', 'Kawardha', 'Kavi', 'Kayamkulam', 'Kayavarohan', 'Kaza', 'Kaziranga National Park', 'Kedarnath', 'Kemmannagundi', 'Kelwa', 'Keonjhar', 'Ketkawale', 'Kesariya', 'Kevadia', 'Keylong', 'Khajjiar', 'Khairabad', 'Khajuraho', 'Khammam', 'Khalapur', 'Khandwa', 'Kharagpur', 'Khanvel', 'Khargone', 'Khatkar Kalan', 'Kheda', 'Khichan', 'Khed', 'Khetri', 'Khonoma', 'Khodala', 'Khopoli', 'Khonsa', 'Khubi', 'Khordha', 'Khuldabad', 'Khurda', 'Khunti', 'Kishangarh', 'Khurja', 'Kidanganad', 'Kiriburu', 'Kochi (Cochin)', 'Aluva', 'Ernakulam District', 'Fort Kochi', 'Maradu', 'Nedumbassery', 'Paravoor', 'Vaikom', 'Ernakulam District', 'Tripunithura', 'Perumbavoor', 'Angamaly', 'Kaloor', 'Kakkanad', 'Thrikkakara', 'Kodaikanal', 'Kodagurki', 'Kodanad', 'Koderma', 'Kodungallur', 'Kohima', 'Kohka', 'Koilwar', 'Kokrajhar', 'Kolad', 'Kohri', 'Kolar', 'Kolagappara', 'Kolaghat', 'Kolhapur', 'Kolasib', 'Sangli', 'Kollam', 'Kollengode', 'Kollur', 'Konark', 'Kondapalle', 'Konni', 'Koonthakulam', 'Kopargaon', 'Koppal', 'Koraput', 'Koppa', 'Korba', 'Kotagiri', 'Koriya', 'Kota', 'Kotdwara', 'Kothamangalam', 'Kotgarh', 'Kottagudi', 'Kotkhai', 'Kottarakkara', 'Kottayam', 'Kumarakom', 'Manarcaud', 'Kovalam', 'Koynanagar', 'Kovilpatti', 'Kozhikode', 'Krishnagiri', 'Krishnanagar', 'Kuchaman', 'Kudal', 'Kuduremukha', 'Kudli', 'Kudrasthe', 'Kufri', 'Kullu', 'Kulasekharam', 'Kulithalai', 'Kumaon', 'Kumbakonam', 'Thanjavur', 'Kumbhalgarh', 'Kumta', 'Kundapur', 'Kunkeshwar', 'Kupup', 'Kupwara', 'Kurnool', 'Kuravilangad', 'Kurseong', 'Kurukshetra', 'Kuruppampady', 'Kushalnagar', 'Kushinagar', 'Kutch', 'Kuthar', 'Kuttanad', 'Kuttikkanam', 'Lachen', 'Labpur', 'Lachung', 'Laitmawsiang', 'Lakhpat', 'Ladnun', 'Lakhimpur', 'Lalitpur', 'Lakkundi', 'Lansdowne', 'Lataguri', 'Latur', 'Latehar', 'Lavasa', 'Lava', 'Leh', 'Lawngtlai', 'Chimre', 'Lepakshi', 'Loleygaon', 'Lonar', 'Khandala', 'Lonavala', 'Pune', 'Long Island', 'Lucknow', 'Ludhiana', 'Lumding', 'Lunglei', 'Machavaram', 'Machilipatnam', 'Madduru', 'Madhubani', 'Madhugiri', 'Bhagamandala', 'Madikeri', 'Madurai', 'Madla', 'Magadi', 'Madurantakam', 'Mahabaleshwar', 'Nakinda', 'Panchgani', 'Mahabalipuram', 'Mahad', 'Mahasamund', 'Mahbubnagar', 'Mahendragarh', 'Maheshwar', 'Mahuva', 'Mahul Pali', 'Maihar', 'Mailam', 'Mailani', 'Majuli', 'Malappuram', 'Malayattoor', 'Malda', 'Malbazar', 'Malpe', 'Malvan', 'Manali', 'Mamidada', 'Naggar', 'Vashisht', 'Manikaran', 'Mananthavady', 'Manas National Park', 'Mandapeta', 'Mandawa', 'Mandarthi', 'Mandi', 'Mandla', 'Mandore', 'Mandsaur', 'Mandu', 'Mandvi', 'Mysuru (Mysore)', 'Srirangapatna', 'Mandya', 'Mangalagiri', 'Mangaldai', 'Mangalore', 'Mangan', 'Mangar', 'Manipal', 'Mannargudi', 'Manjakuppam', 'Mannady', 'Mannarkkad', 'Mansar', 'Mantralayam', 'Mansa', 'Mappedu', 'Mararikulam', 'Marayur', 'Maravanthe', 'Marthandam', 'Mashobra', 'Marigaon', 'Masinagudi', 'Matheran', 'Mathura', 'Vrindavan', 'Mavelikara', 'Mawlynnong', 'Mawphlang', 'Mayapur', 'Mayiladuthurai', 'Medak', 'Maynaguri', 'Mazbat', 'Mecheri', 'Medicherlapalem', 'Meerut', 'Mehsana', 'Mehkar', 'Melmaruvathur', 'Melukote', 'Mhaismal', 'Menar', 'Meppadi', 'Mhow', 'Midnapore', 'Mira Bhayandar', 'Mirik', 'Mirzapur', 'Modhera', 'Mishrikh Neemsar', 'Moga', 'Mohali', 'Mogra', 'Mokokchung', 'Mollem National Park', 'Mon', 'Moodabidri', 'Moradabad', 'Morbi', 'Morena', 'Morni Hills', 'Mount Abu', 'Mudigere', 'Mudumalai', 'Mukteshwar', 'Muktsar', 'Mukutmanipur', 'Mulbagal', 'Mulshi', 'Mulki', 'Mumbai', 'Chinnakanal', 'Pallivasal', 'Munsiyari', 'Murdeshwar', 'Murshidabad', 'Murthal', 'Murud', 'Mussoorie', 'Muttukadu', 'Muvattupuzha', 'Muzaffarnagar', 'Muzaffarpur', 'Nadiad', 'Nadia', 'Nagaon', 'Nagapattinam', 'Thiruvarur', 'Vaitheeswarankovil', 'Velankanni', 'Nagarhole National Park', 'Nagarjuna Sagar', 'Nagaur', 'Nagercoil', 'Nagothane', 'Nagpur', 'Nagrota', 'Nagrasu', 'Nahan', 'Nainital', 'Nalanda', 'Nalbari', 'Naldurg', 'Nalgonda', 'Nalsarovar', 'Namakkal', 'Namchi', 'Nambol', 'Nameri National Park', 'Namdapha National Park', 'Namsai', 'Nandalur', 'Nanded', 'Nandurbar', 'Nanguneri', 'Nanjangud', 'Narasaraopet', 'Narendranagar', 'Narkanda', 'Nargol', 'Narmada', 'Narlai', 'Narnaul', 'Narsinghpur', 'Narsapur', 'Nashik', 'Nathdwara', 'Naukuchiatal', 'Nattarasankottai', 'Navi Mumbai', 'Navadvipa', 'Navsari', 'Nawalgarh', 'Nawada', 'Nawanshahr', 'Naya Raipur', 'Nayagrh', 'Nazira', 'Neelavara', 'Neemuch', 'Neil Island', 'Nelliyampathy', 'Nelamangala', 'Nellore', 'Netarhat']

In [9]:
intersection = set(unique_cities).intersection(set(cities))

# Convert intersection back to a list if needed
intersection_list = list(intersection)

print(intersection_list)

['Dahej', 'Muvattupuzha', 'Igatpuri', 'Kannur', 'Gudalur', 'Haldwani', 'Kanpur', 'Gangtok', 'Bikaner', 'Bagdogra', 'Kashid', 'Dahanu', 'Kurnool', 'Darjeeling', 'Joshimath', 'Badami', 'Kishangarh', 'Bharuch', 'Kasauli', 'Bhandardara', 'Anandpur Sahib', 'Gwalior', 'Belur', 'Neil Island', 'Kedarnath', 'Bulandshahr', 'Guna', 'Pushkar', 'Dongargarh', 'Balasore', 'Bhavnagar', 'Khopoli', 'Mandi', 'Dakor', 'Dirang', 'Masinagudi', 'Kolhapur', 'Bageshwar', 'Kodaikanal', 'Daman', 'Aizawl', 'Mussoorie', 'Mount Abu', 'Churu', 'Godda', 'Chittoor', 'Gulbarga', 'Karwar', 'Durg', 'Mukutmanipur', 'Gandhinagar', 'Faridkot', 'Nawalgarh', 'Diu', 'Deogarh', 'Coonoor', 'Chakrata', 'Diveagar', 'Neral', 'Jagdalpur', 'Hospet', 'Kohima', 'Kargil', 'Golaghat', 'Bargarh', 'Chikmagalur', 'Matheran', 'Chikhaldara', 'Anantapur', 'Kurukshetra', 'Bharmour', 'Lachung', 'Dindigul', 'Ambikapur', 'Kumarakom', 'Munsiyari', 'Bahraich', 'Jalna', 'Burdwan', 'Agra', 'Bilaspur', 'Guntur', 'Gurdaspur', 'Madurai', 'Chidambaram', 'Karnal', 'Nagpur', 'Mansa', 'Khajjiar', 'Manipal', 'Namakkal', 'Auli', 'Nellore', 'Jalore', 'Aritar', 'Haldia', 'Chiplun', 'Chitradurga', 'Konark', 'Kashipur', 'Malvan', 'Katra', 'Jajpur', 'Karur', 'Bhuj', 'Jharsuguda', 'Hingoli', 'Haveri', 'Chennai', 'Aligarh', 'Amreli', 'Davangere', 'Harnai', 'Mahabaleshwar', 'Shivpuri', 'Mirzapur', 'Bhopal', 'Alwar', 'Nainital', 'Chintpurni', 'Kurseong', 'Nadiad', 'Daltonganj', 'Datia', 'Meerut', 'Jawhar', 'Dhule', 'Keylong', 'Durgapur', 'Digha', 'Jabalpur', 'Morbi', 'Cooch Behar', 'Jaipur', 'Gaya', 'Chamoli', 'Itarsi', 'Hassan', 'Mumbai', 'Bhiwadi', 'Hardoi', 'Ahmednagar', 'Fazilka', 'Guwahati', 'Khajuraho', 'Araku Valley', 'Lava', 'Latur', 'Kushinagar', 'Ambala', 'Kharagpur', 'Karaikal', 'Bhadrachalam', 'Bishnupur', 'Bhusawal', 'Murshidabad', 'Mandsaur', 'Hoshiarpur', 'Panchkula', 'Banswara', 'Hampi', 'Sasan Gir', 'Eluru', 'Sangli', 'Angul', 'Panchgani', 'Chhindwara', 'Dandeli', 'Muzaffarpur', 'Fatehpur', 'Muzaffarnagar', 'Chitrakoot', 'Chaukori', 'Kumbakonam', 'Bahadurgarh', 'Lansdowne', 'Bordi', 'Kottayam', 'Jhalawar', 'Kundapur', 'Bundi', 'Jambughoda', 'Belgaum', 'Loleygaon', 'Karaikudi', 'Namchi', 'Jodhpur', 'Bandipur', 'Kadapa', 'Kangra', 'Chopta', 'Khammam', 'Bhilwara', 'Amritsar', 'Jhajjar', 'Erode', 'Barmer', 'Gulmarg', 'Himmatnagar', 'Ambaji', 'Amboli', 'Ludhiana', 'Giridih', 'Bhadrak', 'Krishnanagar', 'Mangalore', 'Dausa', 'Ajmer', 'Mandawa', 'Mathura', 'Kudal', 'Dhanbad', 'Aurangabad', 'Bhagalpur', 'Kullu', 'Naukuchiatal', 'Pune', 'Gorakhpur', 'Mahabalipuram', 'Asansol', 'Dungarpur', 'Malappuram', 'Chhatarpur', 'Narkanda', 'Bir', 'Agartala', 'Dhamtari', 'Karauli', 'Bakkhali', 'Kakinada', 'Madhubani', 'Devprayag', 'Kanchipuram', 'Dehradun', 'Allahabad', 'Barog', 'Dapoli', 'Jamnagar', 'Akola', 'Karsog', 'Kalpa', 'Karad', 'Dhar', 'Munnar', 'Itanagar', 'Bhalukpong', 'Ganpatipule', 'Ramgarh', 'Jwalamukhi', 'Firozabad', 'Cuttack', 'Hansi', 'Korba', 'Nagaur', 'Chail', 'Hanumangarh', 'Maihar', 'Jhansi', 'Dhanaulti', 'Kollam', 'Jaisalmer', 'Kota', 'Bellary', 'Chittorgarh', 'Hosur', 'Howrah', 'Bagalkot', 'Kapurthala', 'Kalimpong', 'Lakhimpur', 'Kasol', 'Anand', 'Maheshwar', 'Nahan', 'Bhimavaram', 'Jalpaiguri', 'Keonjhar', 'Hoshangabad', 'Nathdwara', 'Darbhanga', 'Mirik', 'Goa', 'Madikeri', 'Mandu', 'Dibrugarh', 'Nanded', 'Bidar', 'Nagaon', 'Leh', 'Jaunpur', 'Moga', 'Gokarna', 'Beed', 'Manali', 'Bijapur', 'Bhojpur', 'Mayiladuthurai', 'Jorhat', 'Kutch', 'Dholpur', 'Hazaribagh', 'Hyderabad', 'Mahbubnagar', 'Azamgarh', 'Bekal', 'Gondia', 'Chandigarh', 'Bharatpur', 'Krishnagiri', 'Amravati', 'Nandurbar', 'Coimbatore', 'Khandwa', 'Ayodhya', 'Haridwar', 'Jalgaon', 'Ankleshwar', 'Chandrapur', 'Malda', 'Bhilai', 'Narnaul', 'Binsar', 'Moradabad', 'Imphal', 'Almora', 'Guhagar', 'Kotagiri', 'Badrinath', 'Kalka', 'Katni', 'Lataguri', 'Dimapur', 'Dewas', 'Bhimtal', 'Kanyakumari', 'Lalitpur', 'Narsinghpur', 'Fatehpur Sikri', 'Mehsana', 'Bhiwani', 'Gandhidham', 'Mohali', 'Lucknow', 'Neemuch', 'Indore', 'Karimnagar', 'Mukteshwar', 'Jalandhar', 'Kausani', 'Faizabad', 'Kolkata', 'Deesa', 'Jhunjhunu', 'Ahmedabad', 'Kaza', 'Kuttikkanam', 'Guptkashi', 'Gangotri', 'Thanjavur', 'Etawah', 'Jamshedpur', 'Balangir', 'Baramati', 'Lachen', 'Dalhousie', 'Lavasa', 'Chamrajnagar']

In [10]:
print(len(cities))
print(len(intersection_list))

1095
367

HOTEL RECOMMENDATION

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_hotel = pd.read_csv('hotel_dataset_kaggle.csv')
df_hotel

,Hotel Name,Landmark,city,highlight_value,Description,hotel_star_rating,Room facilities,latitude,longitude,review_score,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Hotel Sennite,"Near Bus Stand, Abohar",Abohar,NaN,|less,1 star,NaN,30.146782,74.202694,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aarti Guest House,Abohar,Abohar,24 hour business centre|ADSL Internet service|...,|Aarti Guest House is locate in Abohar. As one...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hotel Sethi Residency,NaN,Abohar,24 Hour Check in-Icon|24/7 Power|Banqueting|Do...,|Hotel Sethi Residency offers cozy accommodati...,2 star,Hot/cold Water | Attached Bathroom,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Manwar Garden Resort,NaN,AbuRoad,NaN,NaN,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hotel Bhumi,opposite sai baba temple aburoad,AbuRoad,NaN,|less,1 star,NaN,0,0.000000,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20042,Hotel Sri Silver Inn,Bedford Road,Yercaud,24/7 Power|Extra Bed (On Request)|Front desk|P...,|Hotel Sri Silver Inn is situated in the beaut...,1 star,Telephone | Bathroom Toiletries | Television |...,11.7813,78.217700,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20043,Ziro Valley Resort,NaN,Ziro,NaN,|Ziro Valley Resort is situated in the beautif...,1 star,NaN,27.523662,93.835467,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20044,Hotel Blue Pine,Ziro,Ziro,NaN,|Hotel Blue Pine is situated in the beautiful ...,1 star,NaN,27.543026,93.807663,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20045,MAMA HOME STAY,NaN,Zuluk,NaN,| Hotel Mama Homestay is a budget property loc...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20046,Hotel Palbheu,NaN,Zuluk,24 hour room service|Car rental|Laundry|Parkin...,| Hotel Palbheu is a budget property located i...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_hotel.columns

Index(['Hotel Name', 'Landmark', 'city', 'highlight_value', 'Description',
       'hotel_star_rating', 'Room facilities', 'latitude', 'longitude',
       'review_score', 'Address', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30'],
      dtype='object')

In [5]:
df_hotel.drop(columns=['Landmark','highlight_value','Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30'])
df_hotel

,Hotel Name,Landmark,city,highlight_value,Description,hotel_star_rating,Room facilities,latitude,longitude,review_score,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Hotel Sennite,"Near Bus Stand, Abohar",Abohar,NaN,|less,1 star,NaN,30.146782,74.202694,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aarti Guest House,Abohar,Abohar,24 hour business centre|ADSL Internet service|...,|Aarti Guest House is locate in Abohar. As one...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hotel Sethi Residency,NaN,Abohar,24 Hour Check in-Icon|24/7 Power|Banqueting|Do...,|Hotel Sethi Residency offers cozy accommodati...,2 star,Hot/cold Water | Attached Bathroom,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Manwar Garden Resort,NaN,AbuRoad,NaN,NaN,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hotel Bhumi,opposite sai baba temple aburoad,AbuRoad,NaN,|less,1 star,NaN,0,0.000000,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20042,Hotel Sri Silver Inn,Bedford Road,Yercaud,24/7 Power|Extra Bed (On Request)|Front desk|P...,|Hotel Sri Silver Inn is situated in the beaut...,1 star,Telephone | Bathroom Toiletries | Television |...,11.7813,78.217700,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20043,Ziro Valley Resort,NaN,Ziro,NaN,|Ziro Valley Resort is situated in the beautif...,1 star,NaN,27.523662,93.835467,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20044,Hotel Blue Pine,Ziro,Ziro,NaN,|Hotel Blue Pine is situated in the beautiful ...,1 star,NaN,27.543026,93.807663,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20045,MAMA HOME STAY,NaN,Zuluk,NaN,| Hotel Mama Homestay is a budget property loc...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20046,Hotel Palbheu,NaN,Zuluk,24 hour room service|Car rental|Laundry|Parkin...,| Hotel Palbheu is a budget property located i...,1 star,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

CREATE HOTEL JSON

In [1]:
import os
import pandas as pd
import json

In [3]:
df = pd.read_csv('hotel_dataset.csv')
df

                   City  Latitude  Longitude         Hotels  Places_to_visit
0     Aamby Valley City   18.5726    73.4049  hotels/1.json              NaN
1              Abhaneri   27.0056    76.6102  hotels/2.json              NaN
2            Achooranam   11.5934    76.0131  hotels/3.json              NaN
3          Acharapakkam   12.4077    79.8170  hotels/4.json              NaN
4                Achrol   27.1330    75.9567  hotels/5.json              NaN
...                 ...       ...        ...            ...              ...
1088        Neil Island       NaN        NaN            NaN              NaN
1089      Nelliyampathy       NaN        NaN            NaN              NaN
1090        Nelamangala       NaN        NaN            NaN              NaN
1091            Nellore       NaN        NaN            NaN              NaN
1092           Netarhat       NaN        NaN            NaN              NaN

[1093 rows x 5 columns]

In [77]:
import os
import pandas as pd
import json

# Assuming you have a DataFrame named df with a column named 'hotels' containing file paths

# Function to extract relevant information from each JSON file
def process_json_file(file_path):
    if os.path.getsize(file_path) == 0:
        print(f"Skipping empty file: {file_path}")
        return None
    
    with open(file_path, 'r') as file:
        data = json.load(file)
    
    places_with_reviews = []
    for place in data["places"]:
        name = place.get("displayName", {}).get("text", "Unknown")  # Extracting name from "displayName" field
        rating = place.get("rating", "Unknown"),
        address = place.get("formattedAddress"),
        reviews = []
        for review in place.get("reviews", []):
            # Check if the review dictionary contains a "text" field
            if "text" in review:
                review_text = review["text"]
                # Check if the review_text is a dictionary with nested "text" and "languageCode" fields
                if isinstance(review_text, dict) and "text" in review_text and "languageCode" in review_text:
                    review_info = {
                        "text": review_text["text"],  # Extracting the text
                        "languageCode": review_text["languageCode"],  # Extracting the language code
                        "rating": rating  # Include rating for each review
                    }
                    reviews.append(review_info)
        
        place_info = {
            "name": name,
            "rating": rating,
            "address": address,
            "reviews": reviews
        }
        places_with_reviews.append(place_info)
    
    return {"places_with_reviews": places_with_reviews}

# Iterate over each file path in the first 198 rows of the DataFrame
for file_path in df['Hotels'][:198]:
    # Process the JSON file
    new_json_data = process_json_file(file_path)
    
    # Check if the JSON data is None (indicating an empty file)
    if new_json_data is None:
        continue
    
    # Extract the current file name
    file_name = os.path.basename(file_path)
    
    # Create a new JSON file path with a dynamic name
    new_file_name = file_name.replace('.json', '_short.json')
    new_file_path = os.path.join(os.path.dirname(file_path), new_file_name)
    
    # Write the new JSON data to the new file
    with open(new_file_path, 'w') as new_file:
        json.dump(new_json_data, new_file, indent=2)

    print(f"Processed: {file_path}. Created: {new_file_path}")

print("All files processed.")

TypeError: 'str' object is not callable

In [15]:
df.to_csv('hotel_pre_process_data.csv')

In [78]:
df

,City,Latitude,Longitude,Hotels,Places_to_visit,hotel_process,new_file_paths,hotel_final
0,Aamby Valley City,18.5726,73.4049,hotels/1.json,NaN,1_short.json,hotels/preprocessed_1_short.json,hotels/preprocessed_1_short.json
1,Abhaneri,27.0056,76.6102,hotels/2.json,NaN,2_short.json,hotels/preprocessed_2_short.json,hotels/preprocessed_2_short.json
2,Achooranam,11.5934,76.0131,hotels/3.json,NaN,3_short.json,hotels/preprocessed_3_short.json,hotels/preprocessed_3_short.json
3,Acharapakkam,12.4077,79.8170,hotels/4.json,NaN,4_short.json,hotels/preprocessed_4_short.json,hotels/preprocessed_4_short.json
4,Achrol,27.1330,75.9567,hotels/5.json,NaN,5_short.json,hotels/preprocessed_5_short.json,hotels/preprocessed_5_short.json
...,...,...,...,...,...,...,...,...
193,Bhavani,11.4471,77.6840,hotels/194.json,NaN,194_short.json,hotels/preprocessed_194_short.json,hotels/preprocessed_194_short.json
194,Bhavnagar,21.7645,72.1519,hotels/195.json,NaN,195_short.json,hotels/preprocessed_195_short.json,hotels/preprocessed_195_short.json
195,Bhawanipatna,19.9074,83.1642,hotels/196.json,NaN,196_short.json,hotels/preprocessed_196_short.json,hotels/preprocessed_196_short.json
196,Bhilai,21.1938,81.3509,hotels/197.json,NaN,197_short.json,hotels/preprocessed_197_short.json,hotels/preprocessed_197_short.json
197,Bhilwara,25.3407,74.6313,hotels/198.json,NaN,198_short.json,hotels/preprocessed_198_short.json,hotels/preprocessed_198_short.json

In [79]:
import json
import os
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from string import punctuation
from bs4 import BeautifulSoup
import string
import re

# Slice the DataFrame to keep only the first 198 rows
df = df.head(198)

def preprocess_text(text):
    # Decode Unicode escape sequences
    text = text.encode().decode('unicode-escape')
    
    # Remove HTML tags using Beautiful Soup
    text = BeautifulSoup(text, 'html.parser').get_text()
    
    # Convert text to lowercase
    text = text.lower()
    
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    
    # Tokenize text
    tokens = word_tokenize(text)
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    
    # Join tokens back into text
    preprocessed_text = ' '.join(filtered_tokens)
    
    return preprocessed_text

# Create a list to store the new file paths
new_file_paths = []

# Iterate over the rows of the DataFrame
for index, row in df.iterrows():
    # Read the JSON file specified in the 'hotel_process' column
    if index in [42, 75, 85, 97, 134, 183, 198]:
        new_file_paths.append("")
        continue
    file_path = os.path.join("hotels", row['hotel_process'])
    with open(file_path, 'r') as file:
        data = json.load(file)
    
    # Check if the 'places_with_reviews' key exists and it is not empty
    if 'places_with_reviews' in data and data['places_with_reviews']:
        # Preprocess the reviews for each place in the JSON data
        for place in data['places_with_reviews']:
            preprocessed_reviews = []
            for review in place['reviews']:
                # Check if review is a string and not equal to "No review text available"
                if isinstance(review, dict) and 'text' in review and review['text'] != "No review text available":
                    preprocessed_text = preprocess_text(review['text'])  # Directly preprocess the review text
                    preprocessed_reviews.append(preprocessed_text)
            
            # Add preprocessed reviews back into the JSON structure
            place['preprocessed_reviews'] = preprocessed_reviews

        # Save the updated JSON data
        output_file_path = f"hotels/preprocessed_{row['hotel_process']}"
        new_file_paths.append(output_file_path)  # Append the new file path to the list
        with open(output_file_path, 'w') as output_file:
            json.dump(data, output_file, indent=4)

        print(f"Preprocessed data saved: {file_path}")
    else:
        print(f"Skipping empty JSON file: {file_path}")

# Add the new column to the DataFrame
df['hotel_final'] = new_file_paths

# Save the DataFrame to a CSV file
df.to_csv('hotel_final_preprocess.csv', index=False)

print("DataFrame saved to preprocessed_data.csv")

Preprocessed data saved: hotels/1_short.json
Preprocessed data saved: hotels/2_short.json
Preprocessed data saved: hotels/3_short.json
Preprocessed data saved: hotels/4_short.json
Preprocessed data saved: hotels/5_short.json
Preprocessed data saved: hotels/6_short.json
Preprocessed data saved: hotels/7_short.json
Preprocessed data saved: hotels/8_short.json
Preprocessed data saved: hotels/9_short.json
Preprocessed data saved: hotels/10_short.json
Preprocessed data saved: hotels/11_short.json
Preprocessed data saved: hotels/12_short.json
Preprocessed data saved: hotels/13_short.json
Preprocessed data saved: hotels/14_short.json
Preprocessed data saved: hotels/15_short.json
Preprocessed data saved: hotels/16_short.json
Preprocessed data saved: hotels/17_short.json
Preprocessed data saved: hotels/18_short.json
Preprocessed data saved: hotels/19_short.json
Preprocessed data saved: hotels/20_short.json
Preprocessed data saved: hotels/21_short.json
Preprocessed data saved: hotels/22_short.json
Preprocessed data saved: hotels/23_short.json
Preprocessed data saved: hotels/24_short.json
Preprocessed data saved: hotels/25_short.json
Preprocessed data saved: hotels/26_short.json
Preprocessed data saved: hotels/27_short.json
Preprocessed data saved: hotels/28_short.json
Preprocessed data saved: hotels/29_short.json
Preprocessed data saved: hotels/30_short.json
Preprocessed data saved: hotels/31_short.json
Preprocessed data saved: hotels/32_short.json
Preprocessed data saved: hotels/33_short.json
Preprocessed data saved: hotels/34_short.json
Preprocessed data saved: hotels/35_short.json
Preprocessed data saved: hotels/36_short.json
Preprocessed data saved: hotels/37_short.json
Preprocessed data saved: hotels/38_short.json
Preprocessed data saved: hotels/39_short.json
Preprocessed data saved: hotels/40_short.json
Preprocessed data saved: hotels/41_short.json
Preprocessed data saved: hotels/42_short.json
Preprocessed data saved: hotels/44_short.json
Preprocessed data saved: hotels/45_short.json
Preprocessed data saved: hotels/46_short.json
Preprocessed data saved: hotels/47_short.json
Preprocessed data saved: hotels/48_short.json
Preprocessed data saved: hotels/49_short.json
Preprocessed data saved: hotels/50_short.json
Preprocessed data saved: hotels/51_short.json
Preprocessed data saved: hotels/52_short.json
Preprocessed data saved: hotels/53_short.json
Preprocessed data saved: hotels/54_short.json
Preprocessed data saved: hotels/55_short.json
Preprocessed data saved: hotels/56_short.json
Preprocessed data saved: hotels/57_short.json
Preprocessed data saved: hotels/58_short.json
Preprocessed data saved: hotels/59_short.json
Preprocessed data saved: hotels/60_short.json
Preprocessed data saved: hotels/61_short.json
Preprocessed data saved: hotels/62_short.json
Preprocessed data saved: hotels/63_short.json
Preprocessed data saved: hotels/64_short.json
Preprocessed data saved: hotels/65_short.json
Preprocessed data saved: hotels/66_short.json
Preprocessed data saved: hotels/67_short.json
Preprocessed data saved: hotels/68_short.json
Preprocessed data saved: hotels/69_short.json
Preprocessed data saved: hotels/70_short.json
Preprocessed data saved: hotels/71_short.json
Preprocessed data saved: hotels/72_short.json
Preprocessed data saved: hotels/73_short.json
Preprocessed data saved: hotels/74_short.json
Preprocessed data saved: hotels/75_short.json
Preprocessed data saved: hotels/77_short.json
Preprocessed data saved: hotels/78_short.json
Preprocessed data saved: hotels/79_short.json
Preprocessed data saved: hotels/80_short.json
Preprocessed data saved: hotels/81_short.json
Preprocessed data saved: hotels/82_short.json
Preprocessed data saved: hotels/83_short.json
Preprocessed data saved: hotels/84_short.json
Preprocessed data saved: hotels/85_short.json
Preprocessed data saved: hotels/87_short.json
Preprocessed data saved: hotels/88_short.json
Preprocessed data saved: hotels/89_short.json
Preprocessed data saved: hotels/90_short.json
Preprocessed data saved: hotels/91_short.json
Preprocessed data saved: hotels/92_short.json
Preprocessed data saved: hotels/93_short.json
Preprocessed data saved: hotels/94_short.json
Preprocessed data saved: hotels/95_short.json
Preprocessed data saved: hotels/96_short.json
Preprocessed data saved: hotels/97_short.json
Preprocessed data saved: hotels/99_short.json
Preprocessed data saved: hotels/100_short.json
Preprocessed data saved: hotels/101_short.json
Preprocessed data saved: hotels/102_short.json
Preprocessed data saved: hotels/103_short.json
Preprocessed data saved: hotels/104_short.json
Preprocessed data saved: hotels/105_short.json
Preprocessed data saved: hotels/106_short.json
Preprocessed data saved: hotels/107_short.json
Preprocessed data saved: hotels/108_short.json
Preprocessed data saved: hotels/109_short.json
Preprocessed data saved: hotels/110_short.json
Preprocessed data saved: hotels/111_short.json
Preprocessed data saved: hotels/112_short.json
Preprocessed data saved: hotels/113_short.json
Preprocessed data saved: hotels/114_short.json
Preprocessed data saved: hotels/115_short.json
Preprocessed data saved: hotels/116_short.json
Preprocessed data saved: hotels/117_short.json
Preprocessed data saved: hotels/118_short.json
Preprocessed data saved: hotels/119_short.json
Preprocessed data saved: hotels/120_short.json
Preprocessed data saved: hotels/121_short.json
Preprocessed data saved: hotels/122_short.json
Preprocessed data saved: hotels/123_short.json
Preprocessed data saved: hotels/124_short.json
Preprocessed data saved: hotels/125_short.json
Preprocessed data saved: hotels/126_short.json
Preprocessed data saved: hotels/127_short.json
Preprocessed data saved: hotels/128_short.json
Preprocessed data saved: hotels/129_short.json
Preprocessed data saved: hotels/130_short.json
Preprocessed data saved: hotels/131_short.json
Preprocessed data saved: hotels/132_short.json
Preprocessed data saved: hotels/133_short.json
Preprocessed data saved: hotels/134_short.json
Preprocessed data saved: hotels/136_short.json
Preprocessed data saved: hotels/137_short.json
Preprocessed data saved: hotels/138_short.json
Preprocessed data saved: hotels/139_short.json
Preprocessed data saved: hotels/140_short.json
Preprocessed data saved: hotels/141_short.json
Preprocessed data saved: hotels/142_short.json
Preprocessed data saved: hotels/143_short.json
Preprocessed data saved: hotels/144_short.json
Preprocessed data saved: hotels/145_short.json
Preprocessed data saved: hotels/146_short.json
Preprocessed data saved: hotels/147_short.json
Preprocessed data saved: hotels/148_short.json
Preprocessed data saved: hotels/149_short.json
Preprocessed data saved: hotels/150_short.json
Preprocessed data saved: hotels/151_short.json
Preprocessed data saved: hotels/152_short.json
Preprocessed data saved: hotels/153_short.json
Preprocessed data saved: hotels/154_short.json
Preprocessed data saved: hotels/155_short.json
Preprocessed data saved: hotels/156_short.json
Preprocessed data saved: hotels/157_short.json
Preprocessed data saved: hotels/158_short.json
Preprocessed data saved: hotels/159_short.json
Preprocessed data saved: hotels/160_short.json
Preprocessed data saved: hotels/161_short.json
Preprocessed data saved: hotels/162_short.json
Preprocessed data saved: hotels/163_short.json
Preprocessed data saved: hotels/164_short.json
Preprocessed data saved: hotels/165_short.json
Preprocessed data saved: hotels/166_short.json
Preprocessed data saved: hotels/167_short.json
Preprocessed data saved: hotels/168_short.json
Preprocessed data saved: hotels/169_short.json
Preprocessed data saved: hotels/170_short.json
Preprocessed data saved: hotels/171_short.json
Preprocessed data saved: hotels/172_short.json
Preprocessed data saved: hotels/173_short.json
Preprocessed data saved: hotels/174_short.json
Preprocessed data saved: hotels/175_short.json
Preprocessed data saved: hotels/176_short.json
Preprocessed data saved: hotels/177_short.json
Preprocessed data saved: hotels/178_short.json
Preprocessed data saved: hotels/179_short.json
Preprocessed data saved: hotels/180_short.json
Preprocessed data saved: hotels/181_short.json
Preprocessed data saved: hotels/182_short.json
Preprocessed data saved: hotels/183_short.json
Preprocessed data saved: hotels/185_short.json
Preprocessed data saved: hotels/186_short.json
Preprocessed data saved: hotels/187_short.json
Preprocessed data saved: hotels/188_short.json
Preprocessed data saved: hotels/189_short.json
Preprocessed data saved: hotels/190_short.json
Preprocessed data saved: hotels/191_short.json
Preprocessed data saved: hotels/192_short.json
Preprocessed data saved: hotels/193_short.json
Preprocessed data saved: hotels/194_short.json
Preprocessed data saved: hotels/195_short.json
Preprocessed data saved: hotels/196_short.json
Preprocessed data saved: hotels/197_short.json
Preprocessed data saved: hotels/198_short.json
DataFrame saved to preprocessed_data.csv

In [69]:
df

,City,Latitude,Longitude,Hotels,Places_to_visit,hotel_process,new_file_paths
0,Aamby Valley City,18.5726,73.4049,hotels/1.json,NaN,1_short.json,hotels/preprocessed_1_short.json
1,Abhaneri,27.0056,76.6102,hotels/2.json,NaN,2_short.json,hotels/preprocessed_2_short.json
2,Achooranam,11.5934,76.0131,hotels/3.json,NaN,3_short.json,hotels/preprocessed_3_short.json
3,Acharapakkam,12.4077,79.8170,hotels/4.json,NaN,4_short.json,hotels/preprocessed_4_short.json
4,Achrol,27.1330,75.9567,hotels/5.json,NaN,5_short.json,hotels/preprocessed_5_short.json
...,...,...,...,...,...,...,...
193,Bhavani,11.4471,77.6840,hotels/194.json,NaN,194_short.json,hotels/preprocessed_194_short.json
194,Bhavnagar,21.7645,72.1519,hotels/195.json,NaN,195_short.json,hotels/preprocessed_195_short.json
195,Bhawanipatna,19.9074,83.1642,hotels/196.json,NaN,196_short.json,hotels/preprocessed_196_short.json
196,Bhilai,21.1938,81.3509,hotels/197.json,NaN,197_short.json,hotels/preprocessed_197_short.json
197,Bhilwara,25.3407,74.6313,hotels/198.json,NaN,198_short.json,hotels/preprocessed_198_short.json